import {
  faAddressBook,
  faAddressCard,
  faAngry,
  faArchive,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faBackward,
  faBank,
  faBars,
  faBell,
  faBellSlash,
  faBirthdayCake,
  faBook,
  faBookmark,
  faBookOpen,
  faBox,
  faBriefcase,
  faBuilding,
  faCalculator,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarMinus,
  faCalendarPlus,
  faCalendarTimes,
  faCalendarWeek,
  faCamera,
  faChalkboard,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChartSimple,
  faCheck,
  faCirclePlus,
  faClipboardList,
  faClock,
  faCloud,
  faCloudDownload,
  faCloudMoon,
  faCloudSun,
  faCloudUpload,
  faCog,
  faComment,
  faCommentDots,
  faComments,
  faCopy,
  faCreditCard,
  faCube,
  faDatabase,
  faDesktop,
  faDizzy,
  faDownload,
  faEdit,
  faEllipsisH,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExcel,
  faFileImage,
  faFileInvoice,
  faFilePdf,
  faFilePowerpoint,
  faFileSignature,
  faFileUpload,
  faFileWord,
  faFilter,
  faFlag,
  faFlushed,
  faForward,
  faFrown,
  faFrownOpen,
  faGear,
  faGlobe,
  faGraduationCap,
  faGrimace,
  faGrin,
  faGrinAlt,
  faGrinBeam,
  faGrinHearts,
  faGrinSquint,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faHeart,
  faHistory,
  faHome,
  faHourglass,
  faHouse,
  faIdBadge,
  faIdCard,
  faImage,
  faInbox,
  faKey,
  faKeyboard,
  faKiss,
  faKissBeam,
  faKissWinkHeart,
  faLandmark,
  faLanguage,
  faLaptop,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLaughWink,
  faLink,
  faList,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMeh,
  faMehBlank,
  faMehRollingEyes,
  faMicrophone,
  faMobile,
  faMoneyBillTrendUp,
  faMoon,
  faMusic,
  faPalette,
  faPaperPlane,
  faPassport,
  faPause,
  faPen,
  faPhone,
  faPlay,
  faPlus,
  faPlusCircle,
  faPrint,
  faQrcode,
  faRainbow,
  faReceipt,
  faReply,
  faRobot,
  faSackDollar,
  faSadCry,
  faSadTear,
  faSave,
  faSchool,
  faServer,
  faShare,
  faShareAlt,
  faShield,
  faSignOutAlt,
  faSmile,
  faSmileWink,
  faSnowflake,
  faStar,
  faStepBackward,
  faStepForward,
  faStop,
  faStopwatch,
  faSun,
  faSurprise,
  faSync,
  faTablet,
  faThumbsDown,
  faThumbsUp,
  faTimes,
  faTired,
  faTrash,
  faTrashAlt,
  faTriangleExclamation,
  faUniversity,
  faUpload,
  faUser,
  faUserCircle,
  faUserMinus,
  faUserPlus,
  faUsers,
  faUserTie,
  faVideo,
  faVolumeDown,
  faVolumeMute,
  faVolumeUp,
  faWallet,
  faWind,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

// Also import some regular icons if needed
import {
  faAddressCard as faAddressCardRegular,
  faBell as faBellRegular,
  faBookmark as faBookmarkRegular,
  faComment as faCommentRegular,
  faCompass,
  faEnvelope as faEnvelopeRegular,
  faHeart as faHeartRegular,
  faMap,
  faStar as faStarRegular,
} from '@fortawesome/free-regular-svg-icons'

export const icons = {
  // Main Actions
  add: faPlus,
  csv: faFileCsv,
  pdf: faFilePdf,
  excel: faFileExcel,
  invoice: faFileInvoice,
  product: faBox,
  customer: faUsers,
  payroll: faUserTie,
  asset: faBuilding,
  loan: faSackDollar,
  bank: faLandmark,
  budget: faChartPie,
  recurring: faClock,
  tax: faCalculator,
  lock: faLock,
  audit: faClipboardList,
  import: faDownload,
  voice: faMicrophone,
  ai: faRobot,
  printer: faPrint,
  scanner: faCamera,
  clear: faTrash,
  image: faImage,
  copy: faCopy,
  eye: faEye,
  upload: faUpload,
  download: faDownload,
  
  // Navigation
  dashboard: faChartLine,
  transactions: faReceipt,
  inventory: faCube,
  customers: faUsers,
  reports: faChartSimple,
  settings: faGear,
  
  // UI Elements
  search: faMagnifyingGlass,
  filter: faFilter,
  edit: faPen,
  delete: faTrash,
  save: faSave,
  cancel: faTimes,
  close: faXmark,
  check: faCheck,
  right: faArrowRight,
  left: faArrowLeft,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  show: faEye,
  hide: faEyeSlash,
  
  // Theme
  theme: faPalette,
  dark: faMoon,
  light: faSun,
  
  // Security
  blockchain: faLink,
  quantum: faKey,
  
  // Language
  language: faLanguage,
  globe: faGlobe,
  
  // Common
  home: faHouse,
  homeAlt: faHome,
  wallet: faWallet,
  trend: faMoneyBillTrendUp,
  chart: faChartColumn,
  circlePlus: faCirclePlus,
  rotate: faArrowRotateLeft,
  calendar: faCalendar,
  calendarAlt: faCalendarAlt,
  building: faBuilding,
  
  // Customer related
  user: faUser,
  userCircle: faUserCircle,
  email: faEnvelope,
  phone: faPhone,
  location: faLocationDot,
  addressCard: faAddressCard,
  idCard: faIdCard,
  
  // Payroll related
  userTie: faUserTie,
  briefcase: faBriefcase,
  creditCard: faCreditCard,
  userPlus: faUserPlus,
  userMinus: faUserMinus,
  
  // Bank related
  sync: faSync,
  creditcard: faCreditCard,
  qrcode: faQrcode,
  shield: faShield,
  
  // Notifications
  bell: faBell,
  bellRegular: faBellRegular,
  notification: faBell,
  
  // Time
  clock: faClock,
  hourglass: faHourglass,
  stopwatch: faStopwatch,
  
  // Communication
  comment: faComment,
  comments: faComments,
  reply: faReply,
  share: faShareAlt,
  envelope: faEnvelope,
  paperPlane: faPaperPlane,
  
  // File operations
  // upload, download already defined above
  file: faFile,
  fileAlt: faFileAlt,
  fileImage: faFileImage,
  filePdf: faFilePdf,
  fileExcel: faFileExcel,
  
  // Status
  warning: faTriangleExclamation,
  info: faBell,
  error: faTimes,
  success: faCheck,
  
  // Media
  play: faPlay,
  pause: faPause,
  stop: faStop,
  volumeUp: faVolumeUp,
  volumeDown: faVolumeDown,
  volumeMute: faVolumeMute,
  
  // Social
  thumbsUp: faThumbsUp,
  thumbsDown: faThumbsDown,
  star: faStar,
  starRegular: faStarRegular,
  heart: faHeart,
  heartRegular: faHeartRegular,
  bookmark: faBookmark,
  bookmarkRegular: faBookmarkRegular,
  
  // Education
  graduationCap: faGraduationCap,
  school: faSchool,
  university: faUniversity,
  book: faBook,
  bookOpen: faBookOpen,
  
  // Technology
  laptop: faLaptop,
  desktop: faDesktop,
  mobile: faMobile,
  tablet: faTablet,
  server: faServer,
  database: faDatabase,
  cloud: faCloud,
  cloudUpload: faCloudUpload,
  cloudDownload: faCloudDownload,
  
  // Weather
  sun: faSun,
  moon: faMoon,
  cloudSun: faCloudSun,
  cloudMoon: faCloudMoon,
  rainbow: faRainbow,
  wind: faWind,
  snowflake: faSnowflake,
  
  // Emojis/Reactions
  smile: faSmile,
  frown: faFrown,
  meh: faMeh,
  grin: faGrin,
  laugh: faLaugh,
  sad: faSadTear,
  cry: faSadCry,
  angry: faAngry,
  surprise: faSurprise,
  
  // Additional utilities
  cog: faCog,
  settingsGear: faGear,
  signOut: faSignOutAlt,
  archive: faArchive,
  inbox: faInbox,
  starIcon: faStar,
  heartIcon: faHeart,
  flag: faFlag,
  shareIcon: faShareAlt,
  printIcon: faPrint,
  
  // Media controls
  backward: faBackward,
  forward: faForward,
  stepBackward: faStepBackward,
  stepForward: faStepForward,
  
  // File types
  fileWord: faFileWord,
  filePowerpoint: faFilePowerpoint,
  fileArchive: faFileArchive,
  fileCode: faFileCode,
  fileContract: faFileContract,
  fileSignature: faFileSignature,
  fileUpload: faFileUpload,
  fileDownload: faFileDownload,
  
  // Identity
  idBadge: faIdBadge,
  passport: faPassport,
  birthday: faBirthdayCake,
  
  // Calendar operations
  calendarDay: faCalendarDay,
  calendarWeek: faCalendarWeek,
  calendarPlus: faCalendarPlus,
  calendarMinus: faCalendarMinus,
  calendarTimes: faCalendarTimes,
  calendarCheck: faCalendarCheck,
  
  // Communication
  commentDots: faCommentDots,
  envelopeRegular: faEnvelopeRegular,
  
  // Misc
  compass: faCompass,
  map: faMap,
  chalkboard: faChalkboard,
  addressBook: faAddressBook,
  
  // Extra
  plusCircle: faPlusCircle,
  editIcon: faPen,
  trashIcon: faTrashAlt,
  lockIcon: faLock,
  keyIcon: faKey,
  globeIcon: faGlobe,
  languageIcon: faLanguage,
  paletteIcon: faPalette,
  linkIcon: faLink,
  qrCode: faQrcode,
  shieldAlt: faShield,
  userCircleIcon: faUserCircle,
  addressCardRegular: faAddressCardRegular,
  commentRegular: faCommentRegular,
  
  // Custom aliases
  warningIcon: faTriangleExclamation,
  infoIcon: faBell,
  successIcon: faCheck,
  errorIcon: faTimes,
  syncIcon: faSync,
  downloadIcon: faDownload,
  uploadIcon: faUpload,
  print: faPrint,
  scannerIcon: faCamera,
  voiceIcon: faMicrophone,
  robotIcon: faRobot,
  aiIcon: faRobot,
  blockchainIcon: faLink,
  quantumIcon: faKey,
  themeIcon: faPalette,
  darkModeIcon: faMoon,
  lightModeIcon: faSun,
  languageIconAlt: faLanguage,
  globeIconAlt: faGlobe,
  timer: faHourglass,
  menu: faBars,
  more: faEllipsisH,
  trash: faTrash,
  history: faHistory,
  list: faList,
  keyboard: faKeyboard,
}

export { FontAwesomeIcon }

